### ISSUE TITLE
No end credits cutscene

### ISSUE THREAD

**Issue by Emerik1995** [K4thos/Ikemen_GO#53]
I got a bit of a problem with the end credits storyboard I made in the past years.
Here's what I came up with:
```
;Ending credits screen definition
;This screen shows up after the Win Screen and Ending
[End Credits]
enabled = 1               ;Set to 1 to show credits, 0 to disable
storyboard = data/storyboard/EvE_Battle_Credits.def             ;Credits storyboard filename
```
I tired at least 2 methods of showing this cutscene, but to no avail.
```
storyboard = storyboard/EvE_Battle_Credits.def             ;Credits storyboard filename
storyboard = data/storyboard/EvE_Battle_Credits.def             ;Credits storyboard filename
```

**Comment by Emerik1995** [comment]
Instead of showing the end credits, it shows a game over screen.
That's all I asked.

**Comment by K4thos** [comment]
This is not enough info to reproduce it locally. Please upload test build where the issue will be reproducible.

**Comment by Emerik1995** [comment]
Screw this. I'm closing this HARD TO UNDERSTAND issue.

**Comment by K4thos** [comment]
I've spent time trying to reproduce the issue by using storyboards distributed with default screenpack and assigning them the same way as you showcased - didn't notice a problem. And now you're rage closing the issue because I've requested a test build that could help finding where the problem lays?

I suggest reading this article if you don't understand why case being reproducible locally is crucial for fixing bugs: https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

**Comment by Emerik1995** [comment]
Sorry, this issue will remain closed, because I'm autistic (AKA Autism Spectrum Disorder).

**Comment by K4thos** [comment]
it's ok.

I've found 1 problem that may be related to your report - command buffer was not reset at the start of storyboard which could theoretically explain the problem (end credits being skipped when you skip character animation via button press in the last arcade match). It will be fixed in the next build.
