### ISSUE TITLE
[REQUEST] XbrZ Scaler

### ISSUE THREAD

**Issue by shinra358** [K4thos/Ikemen_GO#68]
I would like to request the xbrz scaler so that we can keep our content at 640x480 rezzed items, keeping our game sizes down while at the same time erraticating pixelation and keeping our presentation beautiful.

xbrz source: https://sourceforge.net/p/xbrz/forums/general/
examples:
https://s6.postimg.cc/6feleg801/retroarch_2016-11-23_19-27-06.png
https://s6.postimg.cc/9uhuy9e2p/e_PSXe_2016-11-16_14-32-29.png
https://s6.postimg.cc/ntytmq54x/retroarch_2016-11-23_19-27-28.png
https://s6.postimg.cc/9c1meqdtt/retroarch_2016-11-23_19-45-30.png
https://s6.postimg.cc/cf2ci3ssh/retroarch_2016-11-23_19-25-41.png

Xbrz is a scaler. Not a shader. It cannot be coded externally. It must be internal. Any external xbrz is an immitation and doesnt wrk as it should. The external shader xBR is NOT the same as xbrz. Xbrz in NOT a post processing shader. Again, it is an internal scaler.

**Comment by K4thos** [comment]
from what I see XbrZ scaler uses GPLv3 licence so it's never gonna happen since Ikemen GO is under MIT licence. GPL requires that anything based upon GPL-licensed code must be distributed under the GPL. That restriction applies regardless of whether the code is distributed as source or binary: https://www.gnu.org/licenses/gpl-faq.en.html

**Comment by shinra358** [comment]
Oh ok
