### ISSUE TITLE
Unlockable characters

### ISSUE THREAD

**Issue by shinlucho** [K4thos/Ikemen_GO#7]
It would be nice to have a feature to unlock characters, maybe defeating them like in smash bros or buying them with points. Also it can be related with issue #6

**Comment by K4thos** [comment]
Unlockable characters is in fact already implemented. Quote from select.def:

>  ; - hidden
>  ;   IKEMEN feature: Set the paramvalue to hide a character in a certain
>  ;   way:
>  ;   1: cursor can move to this cell, face and face background
>  ;      are not rendered (same result as hiding selectable characters
>  ;      in mugen by placing them outside visible grid, but without need
>  ;      to create lots of unnecessary select.def slots to do so),
>  ;   2: cell can't be selected, art is not rendered (slot is ignored until
>  ;      character is unlocked).
>  ;   3: cell behaves like randomselect slot until character is unlocked.

select.lua takes it into account for cell background, face rendering and cell movement. There is also select.f_unlockChar(char, flag) function there which can change above mentioned flag during game. 

select.lua takes it into account for cell background, face rendering and cell movement. There is also select.f_unlockChar(char, flag) function there which can change above mentioned flag during game. 
What is missing is a code that would use this function automatically based on game progress. Not yet sure how to implement it (not coding wise - that's easy, but conceptually). Like there should be a way for game maker to decide what actually unlocks which char. Should we add it as optional parameter for [Characters] section of select.def? Or maybe leave it to character's DEF file? Which options should be allowed to unlock it (beating particular game mode with particular character, playing for amount of hours, getting particular score in particular mode etc.) If someone could help designing it conceptually I can write lua code to handle it.

Another thing is an option for full game developers that may be interested in this functionality but without a way for players to bypass the requirements via simple edit. For this some kind of encryption would be needed instead of just saving variables in config.json, although this can wait until the base unlocking is implemented.

**Comment by Mike77154** [comment]
I have a question about this, is it possible to unlock a player when you make sometype of movement in the selection screen? (remember Kof 95 unlocking rugal with start, up+a, down b, you know the classic unlocking boss sequence)

**Comment by Emerik1995** [comment]
Is this the one that came from Smash Ultimate? Once you win at least 5+ matches, a new fighter is available to play.
My description to make a fighter unlockable is this:

> ; - unlock
> ; IKEMEN feature: Set the paramvalue to add any number of winning matches you want to the
> ; character to be unlocked.
> ; Once you set the paramvalue to the character, it will become locked until you reach a higher
> ; number of winning matches.
> ; Once you reached that number of winning matches, the character will be unlocked and become
> ; playable.
> ; If you want to reset your winning matches to zero and start at the beginning, go to Option, select
> ; Game Settings, and select Reset Win Matches.
> ; This will not delete the entire file such as characters & stages. Once you winning matches is set to
> ; zero, all the characters you've unlocked will be locked. This is for the game dev purposes.

**Comment by K4thos** [comment]
implemented in v0.96
