### ISSUE TITLE
New modes request

### ISSUE THREAD

**Issue by DarkD** [K4thos/Ikemen_GO#73]
Shouldn't be that hard to implement with source code on hands so requesting some new modes to spice things up.
- Adventure mode:
The maker chooses characters from roster that are participating in mode(some could be unlocked through the course), between each battle player can change character to one of those, 1 round battles. And storyboards between battles.
- Theft mode:
Regular arcade with a twist that each player starts with 50% of health bar and all damage dealt heals the dealer on same % of health. Could be played in teams with stolen health split among teammates.
- Mirror mode:
Arcade where player plays as same character as opponent. Should be a way to prevent some characters to appear in this mode i.e. giant bosses.
- Parasite mode:
Again, arcade, but player uses defeated enemy as next character played as. Like player starts as Vega, defeats Dan and next battle plays as Dan, wins against Guile there and plays next battle as Guile and so on.
- Curse mode:
Attacks deals no damage, but when character is hit that character becomes marked by curse and it drains health constantly. The only way to lift curse is hit back and pass curse unto opponent. With time curse grows stronger and drains health faster.
- Poison mode:
Again, attacks doesn't deal any damage, but poisoning instead. Poison drains health. Each hit makes poison stronger so health lost faster.
- Stoic mode:
In this mode health and energy are kinda reversed. Start with full energy bar and 25% of health. Energy can't be regained, but instead health is gained how energy would've.
Wanted to suggest 1vs1vs1vs1 for JUS styled games, but remembered that 4 player mode already in works so that's it. Thanks for attention and making ultimate 2D fighting engine, hope those modes would be implemented.

**Comment by K4thos** [comment]
Adventure mode will be possible thanks to the upcoming Story Mode Arcs / Arcade Paths feature. https://github.com/K4thos/Ikemen_GO/wiki/wip

As for the rest, I think these ideas are more suited for some fullgame, with scripts tailored to that specific game needs, rather than general modes available by default with the engine. Next version will come with external modules support, so even if I'm not interested in implementing those modes, you (or someone else) will be able to implement and distribute them without conflicting with ikemen go scripts.

The only remaining modes that I'm interested in working on in future are Tournament Mode and Trials.

**Comment by K4thos** [comment]
Adventure mode

**Comment by PluocTheDragon** [comment]
MK has also the Test your Might mini-game when you have to mash the buttons to build your strength in order to destroy wood plank, heavy stone, and metal anvil.

Strength Mode is a button-mashing game ...and my fingers gets tired! >.<;
